### ISSUE TITLE
Failed to set font family for code-editor

### ISSUE THREAD

**Issue by jwu** [fireball-packages/code-editor#6] opened 2015-08-23 01:36 UTC
I try to setup the font family for code editor like this: https://github.com/fireball-packages/code-editor/commit/02c40b779529013e71a5a3f1acc345f09b5583c1 but failed. 

If I add font-family in .CodeMirror like this:

```css
.CodeMirror {
        height: 100%;
        font-size: 14px;
        font-family: 'DejaVu Sans Mono';
}
```

The font will be applied to code-mirror but the cursor will have wrong position.

**Comment by yorkie** [comment] 2015-08-26 14:00
Hey @jwu I think the correct way to set font is here: https://github.com/fireball-packages/code-editor/blob/master/panel/page.js#L16.

I think this bug is caused by fonts are not aligned.

**Comment by jwu** [comment] 2015-08-26 17:05
Hi @yorkie, what do you mean for fonts are not aligned?

BTW: I have to add `font-family: 'DejaVu Sans Mono';` in `.CodeMirror` otherwise the font will not shows correctly. Here is the screenshot:

without `font-family: 'DejaVu Sans Mono';` in .CodeMirror:


![screen shot 2015-08-27 at 1 03 44 am](https://cloud.githubusercontent.com/assets/174891/9500384/b5a77066-4c57-11e5-9308-317e2a8a570d.png)

with `font-family: 'DejaVu Sans Mono';` in .CodeMirror:

<img width="400" alt="screen shot 2015-08-27 at 1 03 29 am" src="https://cloud.githubusercontent.com/assets/174891/9500386/b870e4b2-4c57-11e5-99ee-cff4a76905f6.png">

**Comment by yorkie** [comment] 2015-08-27 02:28
Ok, reopening

**Comment by yorkie** [comment] 2015-08-29 10:15
Closing this because of https://github.com/fireball-packages/code-editor/pull/7#issuecomment-135968505

**Closed by yorkie** 2015-08-29 10:16 UTC
Labels: bug
